#!c:\Users\felip\OneDrive\Documentos Old\GitHub\PortifolioProjetos\2 Segmentação de clientes\segm_clientes\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
